spring.application.name=Next-Nest

spring.datasource.url=jdbc:mysql://localhost:3306/nextnest_db
spring.datasource.username=username
spring.datasource.password=password

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# JWT
##############################################

app.jwt.secret=secret-key
app.jwt.expiration=604800000

##############################################

file.upload-dir=uploads
spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# Email Configuration
#################################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=XXX@gmail.com
spring.mail.password=mail-password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Spring AI Integration
# Add the Gemini properties
spring.ai.google.genai.api-key=api-key
spring.ai.google.genai.chat.model=gemini-3.6-flash